### ISSUE TITLE
Print out the word IT'S

### ISSUE THREAD

**Issue by cwc-products** [cwc-products/simpleTwo#16]
**Expected behavior**
- [ ] You should see the word "IT'S" printed in the console.

**Additional context**
Having other words printed in the console is ok, but do not let the program "quack"

**Comment by llhowe** [comment]
@intoCareers  Let me know if you have any questions:)

**Comment by intoCareers** [comment]
I don't know what to do.

**Comment by llhowe** [comment]
This may help:) look at #15 (remember to use your word)

**Expected behavior**
- [ ] You should see the word "A" printed in the console.

**Additional context**
- [ ] Having other words printed in the console is ok, but do not let the program "quack"
- [ ] Make the following changes in app.js

**Example**
````
      goDucks.appendMessages([() => 'A']);
````
